### ISSUE TITLE
Scan action just does one beep ?

### ISSUE THREAD

**Issue by nobody1365** [cominixo/OpenLibreNFC#1]
Hi, 

Cool app idea!
Scanning (did'nt try the others so far) just does one "beep" .. no further response or display on the screen ... 
Is it supposed to work with the Libre 2 Sensor / Germany  I use ?

Many Thanks

**Comment by cominixo** [comment]
It does not work with Libre 2, the vulnerabilities are only for non-US Libre 1 sensors unfortunately, and I don't have access to a Libre 2 to do

**Comment by patanito** [comment]
Great idea!! I have downloaded and will test in short with a EU L1, after it stops working with the 12 hr. extension in Xdrip.
For how long is it able to extend the L1 life with an acceptable reliability by calibrating??
My smartphone has NFC, so I guess I should simply select "reset age" and scan. Am I right?

Should it be done before the 14 days of life? Or, can it be done after expiration? Thanks for this!!!!

**Comment by cominixo** [comment]
Yup you just select reset age and scan. I prefer to do it before the 14 days (around 13.9 days), but you can do it in the extra 12 hours after 14 days from what I heard from other people (haven't tried it myself though).
