### ISSUE TITLE
Need more info about System requirements..

### ISSUE THREAD

**Issue by Harry260** [cominixo/OpenLibreNFC#10]

**Comment by cominixo** [comment]
Only requirement should be NFC, I've only tested on android 9+, but should work on some older versions. Full memory dumping is broken for android 11, but everything else works fine,
if you find any issues you can open another issue here

**Comment by Harry260** [comment]
Also, i have one more thing to clarify.. If I reset age with this app, and use the original reader, will it stop working?

**Comment by cominixo** [comment]
It will, yeah, you'll need to use an unofficial app such as xDrip+ or Glimp

**Comment by Harry260** [comment]
Also, it is possible for you to give all the devices that you have tested.?. so I can get on of those :)

**Comment by cominixo** [comment]
If the device is Android 9+ and has NFC it'll work just fine, I've only personally tested on my Moto G6 but tons of people using different phones have gotten it to work, I haven't heard of any phone meeting the requirements I mentioned that doesn't work, so I wouldn't worry too much about it

**Comment by Harry260** [comment]
Oh okay.. Thank you :))
