### ISSUE TITLE
Force close.

### ISSUE THREAD

**Issue by Cybereu** [cominixo/OpenLibreNFC#2]
I was trying to test it but app forces close.

- Android 10 rooted (PixelExperience ROM)
- Redmi Note 7 (don`t have NFC)

Here's logcat:
https://pastebin.com/Er3xzEN7

**Comment by cominixo** [comment]
Thanks for reporting! I'll look into it

**Comment by cominixo** [comment]
Oh, it will crash on phones without NFC, because it can't get the NfcAdapter. Could make it send a message but I don't think there's much point.
