### ISSUE TITLE
Miaomiao support

### ISSUE THREAD

**Issue by Cybereu** [cominixo/OpenLibreNFC#3]
It would be really good feature as many don't have smartphone with NFC reader.

Thanks.

**Comment by cominixo** [comment]
Yeah, the issue with miaomiao is that there isn't really a way (from what I know) to send custom NFC commands with it, just pre defined stuff like reading the memory. If it were possible though, I might consider putting it in xDrip+ instead.

**Comment by Cybereu** [comment]
Thank you for answer.
My solution at the moment is buying the cheapest android with NFC.
There's any requirement I should care about ?

**Comment by cominixo** [comment]
Just NFC should work. Be aware that this only works with non-US Libre 1 sensors
