### ISSUE TITLE
How to use the dump

### ISSUE THREAD

**Issue by exoer** [cominixo/OpenLibreNFC#4]
Thanks for making this app.

I got it running. I did a scan and got a dump file. How do you suggest to use the file? 
I tried to convert the bytes to decimal values, but the numbers doesn't make sense to me. I guess there is a way to convert the raw data to glucose values.

**Comment by cominixo** [comment]
Well not everything in memory is glucose data, you can ignore the first 23 bytes or so, the next 4 will be 2 bytes for a CRC 16 checksum, then two others for trend and history index, then the next 96 bytes will be trend data (which is actually just minute by minute data), then there's history data which should be 192 bytes. Those entries will be raw data and they'll usually be a pretty high number, you can see how all of this works in xDrip+ code or a similar app, haven't looked too much in this part of the memory.
