### ISSUE TITLE
First use in Brazil

### ISSUE THREAD

**Issue by Bbauer120** [cominixo/OpenLibreNFC#5]
Hi, Thanks for the app. Really appreciate! 

i am trying to use the app in brazil but im not pretty sure where the brazilian sensor is from. After a first scan, it shows the sensor is in region 8. is it a region ok? should the app works here?
 also, for the scanning, should i use your app or the ordinary freestyle libre? it didnt show any result when i tried yours. Only a notification saying that it was successfuly scanned. 

thanks for your attention!

**Comment by cominixo** [comment]
Definitely works with Brazilian sensors, since I'm also from Brazil. You can't scan the extended sensors with the official app and reader, so you'll need to use a 3rd party app like xDrip+ or Glimp.

**Comment by Bbauer120** [comment]
That is great!
Im gonna try it!

I'm not sure if you've provided any manual, but it would be awesome.

Muitíssimo obrigado! Abraço

**Comment by cominixo** [comment]
The README explains it a bit, it's really just press the "Reset Age" button and then scan the sensor, then the sensor age will be back to 0, no need to start the sensor again, should just work.
