### ISSUE TITLE
Couldn't dump memory 

### ISSUE THREAD

**Issue by lols11** [cominixo/OpenLibreNFC#6]
When i press "dump memory" button an error message "Couldn't dump memory " is shown
Log: 
https://pastebin.com/nxLd3FMG
I have tried to create the directory and the file manually but the same error is still there.

**Comment by cominixo** [comment]
That's weird, can you tell me your device model and Android version?

**Comment by lols11** [comment]
Redmi Note 8 Pro
MIUI Global 12.0.3
Android 10

**Comment by cominixo** [comment]
Seems like it might be an Android 10 problem, I'll look into it.

**Comment by lols11** [comment]
Function getFile in MainActivity returns path to `/storage/emulated/0/openlibrenfc/memory_dump.txt` 
when proper path is
 `/storage/6331-3264/openlibrenfc/memory_dump.txt`

**Comment by hapvlz** [comment]
Hello Guys,

I have the same problem.
I never had occassion to work with Android code, but I've worked with different languages.

Isn't it caused by this part of code?

```
private File getFile() {
        // External storage path (SD card)
        File sdcard = **Environment.getExternalStorageDirectory();**

        File dir = new File(sdcard.getAbsolutePath() + "/openlibrenfc/");
```

**Environment.getExternalStorageDirectory();**

"This method was deprecated in API level 29.
To improve user privacy, direct access to shared/external storage devices is deprecated. When an app targets Build.VERSION_CODES.Q, the path returned from this method is no longer directly accessible to apps. Apps can continue to access content stored on shared/external storage by migrating to alternatives such as Context#getExternalFilesDir(String), MediaStore, or Intent#ACTION_OPEN_DOCUMENT."

I really want to extend my libre, since it's soo expensive.
Or maybe you already know different ways?

**Comment by hapvlz** [comment]
Ok so, I've rebuilded the project by myself directly in Android Studio and it worked.
Don't ask me how, I do not have fully clue how.

I've tried to move from getExternalStorageDirectory() to getExternalFilesDir()
But I had the same problem, so I just reverted back to original getExternalStorageDirectory(), builded and it worked.

Lane 98 in file MainActivity.java I've added 

`Toast.makeText(this, "Couldn't dump memory to " + file.getAbsolutePath(), Toast.LENGTH_SHORT).show();`

**+ file.getAbsolutePath()**

To see where actually phone is trying to save the data.
Once you try to save dump it will show where it attempted.

/storage/emulated/0/openlibrenfc/memory_dump.txt

So what I did for now is, installed fresh sensor.
Dumped the memory of it.
And after 14 days I'll try to restore load the memory or something.

Not sure yet,  but I don't wanna play too much with the sensor, it's my first one and fresh one so I don't wanna broke it :D

**Comment by cominixo** [comment]
Yeah you don't need to dump/load the memory to extend it, just press the "Reset Age" button and scan it when it's ending

**Comment by hapvlz** [comment]
@cominixo I have question about using NFC modules inside Android Studio, did you manage to run this project on virtual phone inside android studio? I'm getting error that NFC module doesn't exists on virtual phone.

Did you maybe found a way for it?
Thanks :)

**Comment by cominixo** [comment]
Nope, had to test it on my actual phone, as far as I know you can't simulate NFC or anything like that

**Comment by hapvlz** [comment]
Indeed, I couldn't find any way to do that so far :/ It's so problematic as everytime you need to build it, move to phone, install and then just test, for simple debug or anything else it's so time consuming.

**Comment by cominixo** [comment]
Well you don't need to do all that, as long as your phone is connected is should appear as a device in Android Studio and you can just press the run button and it'll install and run it.

**Comment by hapvlz** [comment]
Nice idea, thanks.

**Comment by hapvlz** [comment]
btw. have you tried to load the memory dump of sensor back to sensor? for example after failed reset or any other damage to the sensor?

I wonder if it would be possible to import the dump for ex to different sensor that is damaged.

**Comment by cominixo** [comment]
I've tested the memory dump/load yeah, but not between different sensors, I assume it won't work at all because they have things that are specific to each one in memory, but I really have no idea

**Comment by lols11** [comment]
> btw. have you tried to load the memory dump of sensor back to sensor? for example after failed reset or any other damage to the sensor?
> 
> I wonder if it would be possible to import dump from other new sensor to for ex different sensor that is damaged.

I think that it can't repair the sensor because errors (excluding end of time) are hardware related only i think. I have some sensors to do tests but i don't know how to simulate glucose readings.

**Comment by Cybereu** [comment]
```
private File getFile() {
    // Internal storage path
    File dir = new File(getFilesDir(), "openlibrenfc");
    dir.mkdirs();

    File file = new File(dir, "memory_dump.txt");

    return file;
}
```
Fixed with chatgpt.
